apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: wac
  labels: 
    app: wac
    tier: redis
spec:
  selector:
    matchLabels:
      app: wac
      tier: redis
  template:
    metadata:
      labels:
        app: wac
        tier: redis
    spec:
      shareProcessNamespace: true
      containers:
      - name: shell
        image: harbor.wac/library/busybox:1.28.4
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        stdin: true
        tty: true
      - name: redis
        image: harbor.wac/library/redis:5.0.6
        imagePullPolicy: IfNotPresent
        command:
        - redis-server
        - --requirepass $(REDIS_PASSWORD)
          #- "/usr/local/etc/redis/redis.conf"
        args:
                #- redis-server --requirepass $REDIS_PASSWORD
                #- redis-server --requirepass $REDIS_PASSWORD
        - --appendonly yes
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis
              key: REDIS_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /redis
        - name: logs
          mountPath: /logs
      volumes:
        - name: data
          hostPath: 
            path: /data1/redis/data
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: /data1/redis/log
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: redis
            items:
            - key: redis.properties
              path: redis.conf

